[package]
name = "estromd"
version = "0.1.0"
edition = "2024"

[dependencies]
open = "5.3"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["winit", "markdown"]

[profile.dev.package."*"]
opt-level = 3
